
export enum Channel {
    selectFile = 'select_file',
    ingestdata = 'ingest_data',
    chat = 'chat',
    resources = 'get_resources',
    checkProxy = 'check_proxy',
    checkApiConfig = 'check_apikey',
    outputDirChange = 'output_dir_change',
    apiConfigChange = 'api_config_change',
    showClearHistoryModal = 'show_clear_history_modal',
    showDeleteFileModal = 'showDeleteFileModal',
    renderFileHistoryCleared = 'render_file_history_cleared',
    replyApiConfig = 'reply_api_config',
    proxyChange = 'proxy_change',
    replyProxy = 'reply_proxy',
    requestGetApiConfig = 'request_get_api_config',
    requestGetProxy = 'request_get_proxy',
    requestTestApi = 'request_test_api',
    requestCallGraph = 'request_call_graph',
    findInPage = 'find_in_page',
    stopFindInPage = 'stop_find_in_page',
    electronStoreGet = 'electron_store_get',
    electronStoreSet = 'electron_store_set',
    setRenderCurrentFile = 'set_render_current_file',
    onFoundInPageResult = 'on_found_in_page_result',
    onFound = 'on_found',
    requestOpenFindWindow = 'request_open_find_window',
    setSearchBoxSize = 'set_search_box_size',
    closeSearchWindow = 'close_search_window',
    replyClearHistory = 'reply_clear_history',
    replyDeleteFile = 'reply_delete_file',
    requestllm = 'requestllm',
    sendSignalId = 'send_signal_id'
}
