name: Build Beta
run-name: 'Build Beta ${{ github.event.inputs.name }}'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your build name'
        required: true

jobs:
  build_windows:
    name: Build on Windows
    environment: release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Install MKL
        run: |
          echo "MKLROOT=C:\Program Files (x86)\Intel\oneAPI\mkl\latest" >> $GITHUB_ENV
          .github/workflows/install_mkl_windows.bat "https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/c961e083-5685-4f0b-ada5-c6cf16f561dd/w_BaseKit_p_2023.1.0.47256_offline.exe" "intel.oneapi.win.mkl.devel"
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache Node Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-caches-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-caches-

      - name: Install dependencies
        run: |
          npm i electron-winstaller -D
          npm ci
          npm run copy
      - name: Build package
        run: |
          npm run make-win32

      - name: Get Version
        id: version
        run: |
          $VERSION=$(node -p -e "require('./package.json').version")
          echo $VERSION
          echo VERSION=$VERSION >> $env:GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: out/make/squirrel.windows/x64/*.exe
          tag_name: "v${{ steps.version.outputs.VERSION }}"

  build_macos:
    name: Build on MacOS
    environment: release
    runs-on: macos-11
    permissions:
      contents: write
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Install libomp
        run: |
          brew install libomp
          brew info libomp
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-caches-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-caches-

      - name: Install dependencies
        run: |
          npm i electron-installer-dmg appdmg -D
          npm ci
          npm run copy

      - name: Build package
        run: |
          npm run make-dmg

      - name: Get Version
        id: version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo $VERSION
          echo VERSION=$VERSION >> "$GITHUB_OUTPUT"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: out/make/*.dmg
          tag_name: "v${{ steps.version.outputs.VERSION }}"

